### ISSUE TITLE
Steam integration

### ISSUE THREAD

**Issue by werthen** [ZeusWPI/Lana#10]
- [ ] login with steam
- [ ] display steam information on profile

**Comment by Iepoev** [comment]
what should this do?

Just a link to the steam profile when clicking on an alias? Will we have an account page with general information of a user?

**Comment by ninewise** [comment]
I was wondering how this would be implemented, so I went for quite a short duckduckwalk. You probably know all about this, but I'm linking this here anyway to prevent further walks. [The Steam API](http://steamcommunity.com/dev)

**Comment by werthen** [comment]
@FelixVanderJeugt there actually is a gem that could make integration easier, we could use this
https://github.com/bhaberer/steam-api

**Comment by ninewise** [comment]
Chill.

**Comment by iasoon** [comment]
The only use I see for this is the amount of people playing a certain game, but this is covered by our LFG system.
