### ISSUE TITLE
Time Schedule

### ISSUE THREAD

**Issue by werthen** [ZeusWPI/Lana#11]
The time schedule should contain all upcoming tournaments and events, in a structured fashion.

**Comment by ninewise** [comment]
Integration with #1, it would seem.

**Comment by Procrat** [comment]
http://charts.animateddata.co.uk/f1/

**Comment by werthen** [comment]
https://github.com/jiahuang/d3-timeline

seems like a great solution as well

**Comment by Procrat** [comment]
That one seems indeed better suited for our needs.
