### ISSUE TITLE
User page

### ISSUE THREAD

**Issue by Iepoev** [ZeusWPI/Lana#13]
- [ ] general information of a user 
- LANapp stuff
  - [ ] What groups he's looking for
  - [ ] what records he has in the matches
  - [ ] a timetable for his matches (see #11)
- Steam integration? (see #10)
  - [ ] most played games

**Comment by iasoon** [comment]
Would this add anything to the app?

**Comment by werthen** [comment]
Would it be interesting to display usernames and such that are connected to certain games/services? That way you could also show the appropriate username on group pages.
