### ISSUE TITLE
rename LanApp

### ISSUE THREAD

**Issue by Iepoev** [ZeusWPI/Lana#20]
:D :D :D :D

edit: original suggestion was Lapp

**Comment by werthen** [comment]
ugh idk

**Comment by Iepoev** [comment]
:( :( :( :(

**Comment by TomNaessens** [comment]
Pls don't.

**Comment by Procrat** [comment]
éLAN

> Bring élan to your LAN-party!

**Comment by feliciaan** [comment]
iLan?

**Comment by feliciaan** [comment]
@NoctuaNivalis suggested "Lana" on slack.

**Comment by ninewise** [comment]
I don't think `LOCAL AREA NETWORK APPLICATION`, "Lana" for short, would be bad.

**Comment by werthen** [comment]
Lana it is
