### ISSUE TITLE
Use ActionCable instead of websockets-rails

### ISSUE THREAD

**Issue by werthen** [ZeusWPI/Lana#3]

**Comment by TomNaessens** [comment]
Why is this closed? Is it done? Is there another reason? Adding reasons to closed tickets avoids having to ask this questions.

On 15 Jul 2015 at 20:35:32, Donvittorio (notifications@github.com) wrote:

Closed #3.

**Comment by werthen** [comment]
This was briefly discussed in the rails channel: It's not clear how to properly install this and there might be a lot of changes made, rendering it unstable. The websocket-rails gem -- even though it is a bit more primitive -- will suffice for now.
