### ISSUE TITLE
Shouts/Chatte

### ISSUE THREAD

**Issue by werthen** [ZeusWPI/Lana#8]
- [ ] notification support when a user is mentioned in chat
- [ ] Different chatrooms
- [x] emoji support
- [ ] Colored names
- [ ] twitch emotes

**Comment by ninewise** [comment]
Oh please, emoji's? Are you rewriting twitch?

**Comment by werthen** [comment]
:man_with_gua_pi_mao:

**Comment by werthen** [comment]
@Procrat aub
