### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by werthen** [ZeusWPI/Lana#9]

**Comment by Iepoev** [comment]
we need some list of suggested achievements.

I'm personally against achievments that span multiple years, because it'll complicate account creation and general account stuff

**Comment by ninewise** [comment]
I'm following @Iepoev in this, although for another reason. This is not nice for newbies.

**Comment by werthen** [comment]
One thing I had in mind was: "Winner of the Dota tournament 2015". I get your concern, but for things like that it might be fun.

**Comment by ninewise** [comment]
As a badge on the account page? That does sound nice.

**Comment by werthen** [comment]
That is exactly what I had in mind, renaming the issue because it's a better wording

**Comment by iasoon** [comment]
Since we are not using permanent accounts, is this still relevant?
